### ISSUE TITLE
Cannot click on part of the window of Element variables

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/OsteoBioR#56] opened 2024-07-18 23:28 UTC
Using the files below as reference in the online versions of OsteoBioR, when the window of Element variables is open, it is not possible to see and click the buttons "Select All" and "Deselect All".

[Isotopes.xlsx](https://github.com/user-attachments/files/16286035/Isotopes.xlsx)
[Renewal Rates.xlsx](https://github.com/user-attachments/files/16286036/Renewal.Rates.xlsx)

@arunge

**Comment by arunge** [comment] 2024-08-06 08:57
I checked on Chrome and on Firefox, in both browsers it looks fine and one can apply "Select All" and "Deselect All". The same I tested for my local version having no issues.

### Firefox:
![image](https://github.com/user-attachments/assets/a193351b-ea34-48f7-b842-b153ff451a2b)

### Chrome
![image](https://github.com/user-attachments/assets/3e351961-188c-4516-8a46-6d75d5eac811)

For the input "Time variables" these buttons are not implemented since maximal two time variables are allowed here.

![image](https://github.com/user-attachments/assets/77792915-8382-4118-b1bd-8487db4106fb)

@CarloCocozza  Unfortunately, I cannot reproduce the issue with the data provided above. Do you have some more information?

**Comment by CarloCocozza** [comment] 2024-08-06 12:52
![Capture](https://github.com/user-attachments/assets/6eab4b6e-d733-4b28-a9fc-9d87f8490cc9)

Hi @arunge thanks for looking into this. I attach a screenshot of what happens. I have no idea why this happens, but I noticed that in some occasions (perhaps depending on where is the side bar), the windows open down and not up. The issue arises when it opens up, as in the attached screenshot.

**Comment by arunge** [comment] 2024-08-06 15:23
Ah, ok, now I can reproduce it. It happens when the y-axis of the screen (or the browser window) becomes to small to display the whole data field of the input.

As a solution, I can reduce the number of items to be displayed in the input from 10 to e.g. 5, such that there is more space for the buttons.

![image](https://github.com/user-attachments/assets/96a05b5b-9d06-4687-b77e-3368695aa03b)

@CarloCocozza Would this simple fix help here? Alternatively, you try to increase the y dimension of your window or increase the resolution such that you have more rows in the y dimension. I do not know on which screens you are typically working. Just let me know, what is best for you here!

**Comment by CarloCocozza** [comment] 2024-08-06 15:27
@arunge thank you! Would it be possible to make so that each window only opens down? Some other users may face the same problem, and we don't know what screen would they be using.

**Comment by arunge** [comment] 2024-08-06 15:48
I already tried to change the `windowPadding`, but this did not work that good. I again checked the documentation of the respective function, and there is indeed a parameter to control this, which I tested and it works. I will prepare a fix and let you know when its online.

**Comment by arunge** [comment] 2024-08-08 06:38
@CarloCocozza I set the option that prevents all pickerInputs from dropping up with [version 24.08.0](https://github.com/Pandora-IsoMemo/OsteoBioR/pull/58) which is now available on [OsteoBioR beta online](https://isomemoapp.com/app/osteo-bio-r-beta). I am closing here.

**Closed by arunge** 2024-08-08 06:38 UTC
