### ISSUE TITLE
Results with large s.d. and mean values different from original values

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/OsteoBioR#57] opened 2024-07-18 23:34 UTC
For the attached Renewal rates and isotope files, individual 1 results (stable carbon measurements) have mean results deviating from the original measurements and a very high s.d.
[Isotopes.xlsx](https://github.com/user-attachments/files/16290056/Isotopes.xlsx)
[Renewal Rates.xlsx](https://github.com/user-attachments/files/16290057/Renewal.Rates.xlsx)

I have used both the Beta online version and the local version. The model run in a very elongated time. I attach screenshots of values and times for both versions.
![OsteoBioR Beta Online](https://github.com/user-attachments/assets/56df94ea-6e21-4961-8204-862c18c97c9f)
![OsteoBioR Local](https://github.com/user-attachments/assets/09818698-c0ae-4cce-a7a0-c980aec9316d)

@arunge

**Comment by arunge** [comment] 2024-08-09 10:16
@CarloCocozza Regarding your [comment](https://github.com/Pandora-IsoMemo/OsteoBioR/issues/59#issue-2453971830):
> I attach renewal rates and isotope files for a model that I have run in OsteoBioR version 24.4.1.2 online. The model run in 134 minutes. The model had no issues as the ones reported previously in issue https://github.com/Pandora-IsoMemo/OsteoBioR/issues/57 this time.

Do I understand you correctly that when you ran the same model a second time, the issue from above (large s.d., different mean) did not occur? If not, what was the difference between both models? Did you use different data? Or just different modelling parameters (if so, which)?

**Comment by CarloCocozza** [comment] 2024-08-09 10:58
@arunge those are two different models (different data). The model from issue #59 did not face the same issue with SDs that I observed in model reported in issue #57. I have no idea whether that occurred due to different data or simply in a newer version of OsteoBioR this issue was solved.

**Comment by arunge** [comment] 2024-09-27 13:37
I ran your data with the model with a local version (24.9.3.1) with 2000 iterations. This quickly finished and estimates are close to original data:

![image](https://github.com/user-attachments/assets/974c7d53-3012-49bf-8885-d52169ac2619)

![image](https://github.com/user-attachments/assets/2e64f3b2-57f0-44aa-8bd5-b1d2164600a4)

Online the result looks similar:

![image](https://github.com/user-attachments/assets/5be66f69-aa8d-4d21-b657-b9d7bd8558b9)

When running the model with 5000 iterations locally we do have

![image](https://github.com/user-attachments/assets/66058784-d25f-4bb3-a007-d1a58a2b3e03)

We had no significant updates to the model for a long time, see https://github.com/Pandora-IsoMemo/OsteoBioR/blame/main/R/estimateIntervals.R
So I do not believe that there was an issue that we fixed with a newer version.

However, recently there had been some updates to the `Rcpp` and the `rstan` package since we updated the R version in our docker container to version 4.3.2. For this we had to rebuild the C++ code.
I do not know if this impacts model results. Hopefully, the issue from above does not occur anymore. For now, it was not reproducible and I am closing here. Sorry for not checking this issue earlier!

**Closed by arunge** 2024-09-27 13:37 UTC
